### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by tgeeTechtonic** [broxburyTechtonic/techtonic_slack_shoutout_bot#108]
As a user, I would like to see these areas improve: 

 - [x] Update Nav styling: #133 
 - [x] Update reports page styling: #135
 - [x] Update Monthly Reports styling: #134
 - [x] Update Users Reports styling: #136
 - [x] Update All Shouts Reports styling: #137
