### ISSUE TITLE
Create Users reports view

### ISSUE THREAD

**Issue by tgeeTechtonic** [broxburyTechtonic/techtonic_slack_shoutout_bot#47]
For the component to be completed:

- [x] It should have a DateRangePicker component. See ticket #81 

- [x] It should have a UserDirectory component. See ticket #82

  - [x] Search Bar and Tree View selection component #83
  - [x] Profile Card component #84
  - [x] Expansion Component #85
    - [x] Table for shoutouts given
    - [x] Table for shoutouts received
    - [x] Combined User Summary Table

As a developer,

This component should keep track of:

- [x]  Dates selected

- [x]  Selected userId
